### ISSUE TITLE
Can't install websync TypeError: Cannot read property 'base' of null

### ISSUE THREAD

**Issue by mourningsun75** [furier/websync#12]
Hi,

i have tried to install websync on my old debian server.
First of all i have to install many packages like:

```
sudo npm install -g bower
sudo npm install --global gulp
sudo npm install isarray
sudo npm install core-util-is
sudo npm install inherits
sudo npm install xtend
sudo npm install jshint
sudo npm install map-key
```

Now if i try to build with gulp build i got the following error:

```
/opt/websync/node_modules/gulp-concat-css/index.js:55
      base: firstFile.base,
                     ^
TypeError: Cannot read property 'base' of null
    at Transform._flush (/opt/websync/node_modules/gulp-concat-css/index.js:55:22)
    at Transform.<anonymous> (/opt/websync/node_modules/gulp-concat-css/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at Transform.g (events.js:180:16)
    at Transform.emit (events.js:117:20)
    at finishMaybe (/opt/websync/node_modules/gulp-concat-css/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12)
    at endWritable (/opt/websync/node_modules/gulp-concat-css/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3)
    at Transform.Writable.end (/opt/websync/node_modules/gulp-concat-css/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5)
    at Transform.onend (/opt/websync/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Transform.g (events.js:180:16)
    at Transform.emit (events.js:117:20)
```

Is there some dependency missing?

**Comment by albertovincenzi** [comment]
Same problem in Ubuntu 12.04...
I've tried everything but is not working... The error is the same as reported.

**Comment by codedmind** [comment]
Ubuntu server 14.04 same error

**Comment by peterrus** [comment]
same

npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

ubuntu 14.04

**Comment by mhoskiso** [comment]
I ran into this problem on 14.04 as well, turns out the alertify css file changed names. #34

**Comment by furier** [comment]
Merged pull request #34, didn't have time to verify the PR so please speak up if it messed up things for other users not having this issue...

**Comment by sparklyballs** [comment]
i built succesfully from the latest PR like this 

cd /app/websync
npm install
bower install
gulp dist || true
rm -rf /app/websync/dist
gulp dist

**Comment by sparklyballs** [comment]
in this dockerfile

https://github.com/linuxserver/docker-websync/blob/master/Dockerfile
