### ISSUE TITLE
Build fail at npm install on CentOS 7

### ISSUE THREAD

**Issue by luky83** [furier/websync#52]
$ npm install

> hiredis@0.1.17 install /home/luca/websync/node_modules/hiredis
> node-gyp rebuild

make: Entering directory `/home/luca/websync/node_modules/hiredis/build'
  CC(target) Release/obj.target/hiredis/deps/hiredis/hiredis.o
make: cc: comando non trovato
make: *** [Release/obj.target/hiredis/deps/hiredis/hiredis.o] Errore 127
make: Leaving directory `/home/luca/websync/node_modules/hiredis/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/luca/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.10.0-693.el7.x86_64
gyp ERR! command "/home/luca/.nvm/versions/node/v8.11.1/bin/node" "/home/luca/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/luca/websync/node_modules/hiredis
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@github:pipobscure/fsevents#7dcdf9fa3f8956610fd6f69f72c67bace2de7138 (node_modules/watchify/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.2.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN restangular@1.6.1 requires a peer of angular@>=1.3.12 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hiredis@0.1.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hiredis@0.1.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/luca/.npm/_logs/2018-05-10T09_45_07_156Z-debug.log

**Comment by luky83** [comment]
after
```
nvm install v0.10.31
npm install -g bower
npm install -g gulp
```
npm install fails with:
`npm install
npm WARN package.json browser-resolve@1.11.2 No README data
npm WARN package.json copy-descriptor@0.1.1 No README data
npm WARN package.json dom-serializer@0.1.0 No README data
npm WARN package.json estraverse@4.2.0 No README data
npm WARN package.json get-value@2.0.6 No README data
npm WARN package.json hsb2rgb@1.0.2 No repository field.
npm WARN package.json hsb2rgb@1.0.2 No README data
npm WARN package.json jade@0.26.3 No README data
npm WARN package.json mocha@2.5.3 No README data
npm WARN package.json object-copy@0.1.0 No README data
npm WARN package.json path-is-inside@1.0.2 No README data
npm WARN package.json pstree.remy@1.1.0 No repository field.
npm WARN package.json pstree.remy@1.1.0 No README data
npm WARN package.json static-extend@0.1.2 No README data
npm WARN package.json uid2@0.0.3 No repository field.
npm WARN package.json uid2@0.0.3 No README data
npm WARN package.json assert@1.1.2 assert is also the name of a node core module.
npm WARN package.json batch@0.5.0 No repository field.
npm WARN package.json bcrypt-pbkdf@1.0.1 No repository field.
npm WARN package.json buffer@2.8.2 buffer is also the name of a node core module.
npm WARN package.json bytes@0.2.1 No repository field.
npm WARN package.json callsite@1.0.0 No repository field.
npm WARN package.json color-parser@0.1.0 No repository field.
npm WARN package.json color-parser@0.1.0 repo should probably be repository.
npm WARN package.json colorspace@1.0.1 No repository field.
npm WARN package.json cookie-signature@1.0.1 No repository field.
npm WARN package.json events@1.0.2 events is also the name of a node core module.
npm WARN package.json has-binary@0.1.7 No repository field.
npm WARN package.json indexof@0.0.1 No repository field.
npm WARN package.json object-component@0.0.3 No repository field.
npm WARN package.json pause@0.0.1 No repository field.
npm WARN package.json punycode@1.4.1 punycode is also the name of a node core module.
npm WARN package.json querystring@0.2.0 querystring is also the name of a node core module.
npm WARN package.json range-parser@0.0.4 No repository field.
npm WARN package.json rework-visit@1.0.0 No repository field.
npm WARN package.json string_decoder@0.10.31 string_decoder is also the name of a node core module.
npm WARN package.json url@0.10.3 url is also the name of a node core module.
npm WARN package.json util@0.10.3 util is also the name of a node core module.
/
> hiredis@0.1.17 install /home/luca/websync/node_modules/hiredis
> node-gyp rebuild

make: Entering directory `/home/luca/websync/node_modules/hiredis/build'
  CC(target) Release/obj.target/hiredis/deps/hiredis/hiredis.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/net.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/async.o
  AR(target) Release/obj.target/deps/hiredis.a
  COPY Release/hiredis.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
  CXX(target) Release/obj.target/hiredis/src/reader.o
  SOLINK_MODULE(target) Release/obj.target/hiredis.node
  SOLINK_MODULE(target) Release/obj.target/hiredis.node: Finished
  COPY Release/hiredis.node
make: Leaving directory `/home/luca/websync/node_modules/hiredis/build'

> gifsicle@0.1.7 postinstall /home/luca/websync/node_modules/gifsicle
> node index.js


/home/luca/websync/node_modules/request/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/luca/websync/node_modules/request/node_modules/hawk/lib/index.js:5:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! gifsicle@0.1.7 postinstall: `node index.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the gifsicle@0.1.7 postinstall script.
npm ERR! This is most likely a problem with the gifsicle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls gifsicle
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.10.0-693.el7.x86_64
npm ERR! command "/home/luca/.nvm/v0.10.31/bin/node" "/home/luca/.nvm/v0.10.31/bin/npm" "install"
npm ERR! cwd /home/luca/websync
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/luca/websync/npm-debug.log
npm ERR! not ok code 0
`
